import type { TaskDocumentInput } from "./types.js";

const now = "2026-04-12T12:00:00.000Z";

export const sampleTasks: TaskDocumentInput[] = [
  {
    code: "S1",
    project: "cortex",
    short_task: "Inicializar modelo de tareas",
    detail: "Base inicial del dominio y sincronización con Mongo.",
    status: "DONE",
    agent: "atlas",
    severity: "MEDIUM",
    tags: ["backend", "foundation"],
    depends_on: [],
    duration_estimate: 2,
    lane: "Foundation",
    order_hint: 1,
    source_ref: "seed",
    created_at: now,
    updated_at: now
  },
  {
    code: "S2",
    project: "cortex",
    short_task: "Repositorio Mongo para tareas",
    detail: "Persistencia primaria de tareas y consultas base.",
    status: "DONE",
    agent: "atlas",
    severity: "HIGH",
    tags: ["backend", "mongo"],
    depends_on: ["S1"],
    duration_estimate: 3,
    lane: "Foundation",
    order_hint: 2,
    source_ref: "seed",
    created_at: now,
    updated_at: now
  },
  {
    code: "S2.1",
    project: "cortex",
    short_task: "Construcción del grafo PERT",
    detail: "Normalización, índices y snapshot estable del DAG.",
    status: "IN_PROGRESS",
    agent: "atlas",
    severity: "HIGH",
    tags: ["backend", "graph"],
    depends_on: ["S2"],
    duration_estimate: 5,
    lane: "Graph",
    order_hint: 3,
    source_ref: "seed",
    created_at: now,
    updated_at: now
  },
  {
    code: "S3",
    project: "cortex",
    short_task: "Sidebar operacional en VS Code",
    detail: "Tree views con ready tasks, bloqueadas y filtros.",
    status: "PENDING",
    agent: "sevastopol",
    severity: "MEDIUM",
    tags: ["frontend", "vscode"],
    depends_on: ["S2.1"],
    duration_estimate: 4,
    lane: "Extension",
    order_hint: 4,
    source_ref: "seed",
    created_at: now,
    updated_at: now
  },
  {
    code: "S4",
    project: "cortex",
    short_task: "Servidor MCP para automatización",
    detail: "Tools, resources y prompts sobre tareas y grafo.",
    status: "PENDING",
    agent: "nomad",
    severity: "HIGH",
    tags: ["backend", "mcp"],
    depends_on: ["S2.1"],
    duration_estimate: 4,
    lane: "Automation",
    order_hint: 5,
    source_ref: "seed",
    created_at: now,
    updated_at: now
  },
  {
    code: "S5a",
    project: "cortex",
    short_task: "Definir pricing versionado",
    detail: "Tabla centralizada de precios y billing mode.",
    status: "PENDING",
    agent: "telemetry",
    severity: "MEDIUM",
    tags: ["telemetry", "cost"],
    depends_on: [],
    duration_estimate: 2,
    lane: "Telemetry",
    order_hint: 6,
    source_ref: "seed",
    created_at: now,
    updated_at: now
  },
  {
    code: "S5b",
    project: "cortex",
    short_task: "UI editor de parámetros comunes",
    detail: "Webview PERT con detalle y metadatos calculados.",
    status: "BLOCKED",
    agent: "sevastopol",
    severity: "MEDIUM",
    tags: ["frontend", "admin"],
    depends_on: ["S5a", "S2.1"],
    duration_estimate: 6,
    lane: "Extension",
    order_hint: 7,
    source_ref: "seed",
    created_at: now,
    updated_at: now
  }
];
