// Glosario de Brain. Se inyecta en un preview de markdown via el host
// (markdown.showPreview), igual que el glosario de Script Flow.

export const BRAIN_GLOSSARY_MD = [
  "# Brain — Glosario de nodos y flechas",
  "",
  "Brain analiza una carpeta de `.md`/`.mdx` y construye un grafo con los documentos, sus relaciones, la estructura de árbol y los problemas detectados.",
  "",
  "## Tipos de nodo",
  "",
  "| Nodo | Qué es | De dónde sale |",
  "|---|---|---|",
  "| **doc** | Una página `.md`/`.mdx`. | Cada archivo escaneado. |",
  "| **tag** | Una etiqueta. | Frontmatter `tags:` de los docs. |",
  "| **account** | Una cuenta contable (dominio jean d'arc). | Frontmatter `related.accounts` o el patrón `/manual-cuentas/NNNN/`. |",
  "| **external** | Un destino que no existe en la carpeta. | Links/refs que no resuelven a ningún doc (refs rotas / externas). |",
  "",
  "## Tipos de flecha (relaciones)",
  "",
  "| Flecha | Qué significa | De dónde sale |",
  "|---|---|---|",
  "| **link** | Un doc enlaza a otro doc. | Links markdown `[..](..)` o wikilinks `[[..]]` en el cuerpo. |",
  "| **upstream** | Hacia el padre en el árbol de carpetas. | Sintetizado de la estructura de carpetas (padre = `index.md` más cercano hacia arriba). |",
  "| **downstream** | Hacia los hijos en el árbol de carpetas. | Inverso de upstream. |",
  "| **references** | Referencia explícita entre docs. | Frontmatter `related.references`. |",
  "| **standards** | Norma/estándar referenciado (dominio jean d'arc). | Frontmatter `related.standards`. |",
  "| **account** | El doc menciona una cuenta. | doc → nodo account. |",
  "| **tag** | El doc tiene una etiqueta. | doc → nodo tag. |",
  "| **unresolved** | Flecha **punteada** hacia un nodo `external`: el link/ref apunta a algo que no existe. | Refs rotas. |",
  "",
  "## Vistas (presets)",
  "",
  "| Preset | Muestra |",
  "|---|---|",
  "| **Docs** | Solo los documentos, sin relaciones (planos). |",
  "| **Folder** | Los documentos colgando del árbol de carpetas (upstream/downstream). |",
  "| **Refs** | Todos los kinds + todas las relaciones, en layout orbital. |",
  "| **Full** | Todo: todos los kinds y todas las flechas. |",
  "",
  "## Problemas detectados",
  "",
  "| Problema | Qué es |",
  "|---|---|",
  "| **orphan** | Doc que no cuelga del árbol (sin upstream/downstream). |",
  "| **cycle** | Ciclo en el árbol upstream/downstream (debería ser acíclico). |",
  "| **broken-ref** | Una referencia (references/standards) apunta a algo inexistente. |",
  "| **self-reference** | Un doc se enlaza a sí mismo. |",
  "| **truncated** | El escaneo alcanzó `cortex.brainMaxFiles`; faltan archivos por analizar. |",
  "",
  "## Notas",
  "",
  "- **upstream/downstream** dependen de la estructura de carpetas. Si la carpeta no usa `index.md` por directorio, la jerarquía puede no aparecer.",
  "- **standards/account** son específicos del dominio jean d'arc (contabilidad). En carpetas genéricas están vacíos y se ocultan salvo que se habiliten.",
].join("\n");
