// Mantener sincronizado con docs/script-flow-kinds.md — esta constante se inyecta
// en el panel via vscode.workspace.openTextDocument({ content, language: 'markdown' }).
// Si actualizás el .md, actualizá esta constante (o viceversa).

export const SCRIPT_FLOW_GLOSSARY_MD = [
  "# Script Flow — Glosario de nodos y aristas",
  "",
  "Script Flow analiza un archivo de código (TypeScript, JavaScript, Python o SQL) y produce un grafo dirigido que representa su flujo de ejecución. Este documento describe los tipos de nodos y aristas que pueden aparecer en el panel.",
  "",
  "## Visión general",
  "",
  "El panel consume un `ScriptFlowSnapshot` con:",
  "",
  "- `metadata`: ruta, lenguaje detectado, hash sha1 del source y timestamp del análisis.",
  "- `nodes`: arreglo de nodos tipados (ver tabla abajo).",
  "- `edges`: arreglo de aristas tipadas (ver tabla abajo).",
  "- `analysis`: resumen con entry points, decisiones, loops y observaciones.",
  "",
  "El análisis ocurre en el extension host (no en el webview). El snapshot se postea al panel React + React Flow + dagre.",
  "",
  "## Lenguajes soportados",
  "",
  "| Lenguaje | Extensiones | Parser |",
  "|---|---|---|",
  "| `typescript` | `.ts`, `.tsx`, `.js`, `.jsx` | TypeScript compiler API (`ts.createSourceFile`) |",
  "| `python` | `.py` | tree-sitter-python (WASM) |",
  "| `sql` | `.sql` | node-sql-parser (PostgreSQL + MySQL dialects) |",
  "",
  "Nota: `.js` y `.jsx` caen bajo el umbrella `typescript` por histórico de schema, pero el analyzer setea `ScriptKind.JS` / `JSX` correctamente.",
  "",
  "## Tipos de nodos (`ScriptFlowNodeKind`)",
  "",
  "| Kind | Descripción | Lenguajes que lo emiten | `meta` típico |",
  "|---|---|---|---|",
  "| `entry` | Punto de entrada del documento (nombre del archivo). También se usa como fallback cuando el analyzer SQL no puede parsear el source. | TS, Python | `reason: 'parser-failed'` (fallback) |",
  "| `function` | Función declarada, arrow function, function expression o método de clase. | TS, Python | `async: true` cuando aplica |",
  "| `branch` | Condicional `if`/`else` o `switch`. | TS, Python | `branches: number` (ramas detectadas) |",
  "| `loop` | Bucle `for`, `for-of`, `for-in`, `while`, `do-while`. | TS, Python | `kind: 'for' | 'for-of' | 'for-in' | 'while' | 'do'` |",
  "| `tryCatch` | Bloque try/catch/finally o try/except/else/finally. **Subdividido en sub-nodos** (ver subKinds abajo). | TS, Python | `subKind` requerido; `exceptionType` para Python `except <Type>:` |",
  "| `return` | Sentencia `return` con o sin expresión. | TS, Python | — |",
  "| `call` | Invocación a función relevante (top-level o dentro de un bloque). También SQL no-SELECT (INSERT, UPDATE, DELETE, CREATE, DROP, ALTER, USE). | TS, Python, SQL | `dialect`, `sqlType` (SQL) |",
  "| `cte` | Common Table Expression (`WITH name AS (...)`). | SQL | `dialect` |",
  "| `select` | Statement SELECT (con sus columnas + FROM resuelto en el grafo). | SQL | `dialect` |",
  "| `join` | JOIN dentro de un FROM (inner, left, right, full, cross). | SQL | `joinType`, `target` |",
  "| `subquery` | Subconsulta dentro de FROM, WHERE IN, o JOIN. | SQL | — |",
  "",
  "### Sub-kinds (`meta.subKind`)",
  "",
  "Introducidos en CMP-SCFLOW-08 para granularidad de try/catch sin expandir el schema:",
  "",
  "| `subKind` | Aparece en | Significado |",
  "|---|---|---|",
  "| `try` | `tryCatch` | Bloque `try`. Inicio del manejo de excepciones. |",
  "| `catch` | `tryCatch` | Handler `catch (e)` de TS/JS. |",
  "| `finally` | `tryCatch` | Bloque `finally` (TS/Python). Se ejecuta siempre. |",
  "| `except` | `tryCatch` | Handler `except` de Python. Puede tener `exceptionType` (ej. `\"ValueError\"`). |",
  "| `else` | `tryCatch` | Cláusula `else` de Python `try/except/else/finally`. Corre si no hubo excepción. |",
  "| `parser-failed` | `entry` | Fallback de SCFLOW-02-1 cuando node-sql-parser no entiende el source. Las `observations` describen el error. |",
  "",
  "### Flag `async`",
  "",
  "Funciones marcadas con `async` (`async function`, `async () =>`, `async def`, `class { async m() {} }`) llevan `meta.async: true`. El panel muestra un chip \"async\" en el header del nodo.",
  "",
  "## Tipos de aristas (`ScriptFlowEdgeKind`)",
  "",
  "| Kind | Significado | Cuándo aparece |",
  "|---|---|---|",
  "| `flow` | Flujo de ejecución secuencial. La mayoría de las aristas. | Conecta sentencias dentro de funciones, ramas de branch, body de loops, sub-nodos de tryCatch. |",
  "| `call` | Invocación: el nodo origen llama al destino. | Reservado para futuras extensiones (cross-file references). |",
  "| `dataflow` | Dependencia de datos. | SQL: CTE referenciada → SELECT que la usa; subqueries hacia su contenedor. |",
  "",
  "### Labels comunes en aristas",
  "",
  "| Label | Significado |",
  "|---|---|",
  "| `then` / `else` | Ramas de un `if` |",
  "| `case <expr>` / `default` | Cláusulas de un `switch` |",
  "| `loop` | Backedge del cuerpo del loop al header (animado) |",
  "| `throws` | try → catch / except |",
  "| `after` | try o catch → finally |",
  "| `no exception` | try → else (Python) |",
  "",
  "## Ejemplos prácticos",
  "",
  "### IF / ELSE (TypeScript)",
  "",
  "```ts",
  "if (user.isAdmin) { grant(); } else { deny(); }",
  "```",
  "",
  "Produce: 1 `branch` (\"if user.isAdmin\") con `branches: 2` y aristas con labels `then` y `else` apuntando a 2 `call` nodes (`grant()`, `deny()`).",
  "",
  "### FOR-OF (TypeScript)",
  "",
  "```ts",
  "for (const item of items) { process(item); }",
  "```",
  "",
  "Produce: 1 `loop` con `meta.kind: 'for-of'`, 1 `call` (`process()`), arista flow del loop al call, y un backedge animado del call al loop con label `loop`.",
  "",
  "### try/catch/finally (TypeScript, post-SCFLOW-08)",
  "",
  "```ts",
  "async function load() {",
  "  try { return await fetch('/x'); }",
  "  catch (e) { console.error(e); throw e; }",
  "  finally { cleanup(); }",
  "}",
  "```",
  "",
  "Produce: 1 `function` con `async: true`, y 3 nodos `tryCatch` (subKind try / catch / finally). Aristas: try → catch (label `throws`), try → finally (label `after`), catch → finally (label `after`).",
  "",
  "### try/except/else/finally (Python)",
  "",
  "```python",
  "async def load():",
  "    try:",
  "        return await client.get()",
  "    except ValueError as e:",
  "        raise",
  "    except KeyError:",
  "        return None",
  "    else:",
  "        commit()",
  "    finally:",
  "        close()",
  "```",
  "",
  "Produce: 1 `function` con `async: true`, sub-nodos `tryCatch` (try, 2 except con `exceptionType: 'ValueError'` y `'KeyError'`, else, finally). Aristas con labels `throws`, `no exception`, `after`.",
  "",
  "### CTE + JOIN (SQL)",
  "",
  "```sql",
  "WITH active AS (SELECT id FROM users WHERE active)",
  "SELECT a.id, p.name FROM active a JOIN profiles p ON a.id = p.user_id;",
  "```",
  "",
  "Produce: 1 `cte` (\"CTE active\"), 1 `select`, 1 `join` (\"INNER JOIN profiles\"). Arista `dataflow` de la cte al select. Arista `flow` del select al join.",
  "",
  "### SQL no-SELECT (post-SCFLOW-02)",
  "",
  "```sql",
  "CREATE TABLE products (id INT, name TEXT);",
  "INSERT INTO products VALUES (1, 'cortex');",
  "SELECT name FROM products WHERE id = 1;",
  "```",
  "",
  "Produce: 3 entry points: 2 `call` (CREATE products, INSERT products con `sqlType` y `dialect`) y 1 `select`. Sin aristas entre statements (cada uno es flow independiente).",
  "",
  "### SQL no soportado (post-SCFLOW-02-1)",
  "",
  "```sql",
  "CREATE FUNCTION foo() RETURNS TABLE(ids uuid[]) LANGUAGE plpgsql AS $$ ... $$;",
  "```",
  "",
  "Produce: 1 `entry` con label \"Unsupported SQL syntax\", `meta.reason: 'parser-failed'`, y `analysis.observations` describiendo el error de los parsers PostgreSQL y MySQL.",
  "",
  "## Observaciones típicas (`analysis.observations`)",
  "",
  "Cada analyzer agrega notas al campo `observations` cuando detecta patrones notables. Aparecen en el drawer derecho del panel.",
  "",
  "| Observación | Origen |",
  "|---|---|",
  "| \"Function `<name>` has no explicit return.\" | TS/Python — alerta de control de flujo implícito |",
  "| \"Catch block is empty near line N.\" | TS — catch silencioso |",
  "| \"Empty except block near line N.\" | Python — except silencioso |",
  "| \"No top-level function flow was detected in this file.\" | TS — archivos sin functions top-level |",
  "| \"Cartesian join detected in `<label>`.\" | SQL — JOIN sin ON ni USING |",
  "| \"SELECT * detected in `<label>`.\" | SQL — wildcard projection |",
  "| \"PostgreSQL parser: ...\" / \"MySQL parser: ...\" | SQL — detalle de fallos del parser |",
  "",
  "## Limitaciones conocidas",
  "",
  "- **SQL**: `node-sql-parser` no soporta PL/pgSQL function bodies (`AS $$...$$`), array types (`uuid[]`, `text[]`), `RETURNS TABLE`, `DO` blocks ni meta-commands de psql (`\\connect`, `\\set`). Archivos con esta sintaxis caen al fallback `entry: Unsupported SQL syntax` y muestran los errores del parser en `observations`.",
  "- **Python**: requiere `web-tree-sitter.wasm` + `tree-sitter-python.wasm` en `media/`. El build los copia y verifica su presencia.",
  "- **TypeScript**: no respeta el `tsconfig.json` del workspace — usa `ts.ScriptTarget.Latest` sin compilerOptions. Decoradores experimentales, paths aliases y JSX pragma custom pueden no parsear bien.",
  "- **Generators / async generators**: no se distinguen visualmente.",
  "",
  "## Ver también",
  "",
  "- `docs/modules/script-flow.md` — análisis técnico del módulo (debilidades, decisiones).",
  "- `README.md` — instrucciones de uso e instalación."
].join("\n");
